### ISSUE TITLE
Redo documentation animations

### ISSUE THREAD

**Issue by AndydeCleyre** [AndydeCleyre/zpy#35]
e.g. the one at https://zpy.readthedocs.io/en/latest/pipz/

```yaml
pipz.md: Animated demo: pipz install, list
new_proj/pipacs.md: Animated demo: pipacs
new_proj/pyproject.md: Animated demo: pypc
new_proj/run.md: Animated demo: envin, run script
```

- [x] pipz_install_list
- [x] pipacs
- [x] pypc
- [x] envin/run
